name: admin-ui-extension
namespace: official
version: 1.2.0-2
author: Wazo Team
display_name: Extensions
min_wazo_version: 18.01
tags:
  - beta
homepage: https://github.com/wazo-pbx/wazo-admin-ui-extension
