name: admin-ui-extension
namespace: official
version: 1.1.0
author: Wazo Team
display_name: Extensions
min_wazo_version: 17.17
tags:
  - beta
homepage: https://github.com/wazo-pbx/wazo-admin-ui-extension
